name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build e Testes Automatizados (.NET 8)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore

    - name: Build (Release)
      run: dotnet build --no-restore --configuration Release

    - name: Rodar Testes Automatizados
      run: dotnet test --no-build --configuration Release --verbosity normal 